import { News, NewsType } from "../model/news";

const defaultNews: News[] = [
	{
		type: "absence",
		id: "1",
		date: new Date("2021-09-01"),
		tags: [NewsType.ABSENCE],
		teacherName: "Monsieur ABE",
		teacherMonogram: "ABE",
		teacherGender: "M",
		className: "SAR-MAT2",
		classCode: "SAR-MAT2",
		classStartTime: new Date("2021-09-01T08:00:00"),
		classEndTime: new Date("2021-09-01T10:00:00"),
		groupCode: "SAR-MAT2",
		title: "Absence de Monsieur ABE",
		description: "Monsieur ABE sera absent ce jeudi 1er septembre. Le cours de SAR-MAT2 de 8h est donc annulé et reporté à une date ultérieure.",
	},
	{
		type: "ce",
		id: "2",
		date: new Date("2021-09-01"),
		tags: [NewsType.CE],
		title: "Candidature élections CE",
		description: "Par ce mail le Conseil Étudiant de la HE2B annonce l'ouverture de la période des élections pour la période académique 2025-2026. Vous trouverez dans ce mail notre Règlement Électoral, le calendrier électoral ainsi qu'une copie de la liste des électeur·trice·s de la HE2B.",
	},
	{
		type: "sar",
		id: "3",
		date: new Date("2021-09-02"),
		tags: [NewsType.SAR],
		title: "Réorientation HE2B",
		description: "Après avoir terminé votre session d'examens, il est possible que vous ayez des doutes sur votre orientation actuelle. Peut-être ne savez-vous pas quoi faire ?",
	},
	{
		type: "absence",
		id: "4",
		date: new Date("2021-02-06"),
		tags: [NewsType.ABSENCE, NewsType.SAR, "esi", "mat2"],
		title: "Absence XYZ",
		teacherMonogram: "xyz",
		description: "M. XYZ sera absent ce jeudi 6 février. Le cours de SAR-MAT2 de 16h est donc annulé et reporté à une date ultérieure.",
	},
	{
		type: "marks",
		id: "5",
		date: new Date("2021-09-03"),
		tags: [NewsType.MARKS],
		className: "SAR-MAT2",
		classCode: "SAR-MAT2",
		title: "Résultats de la session",
		description: "Les résultats de la session de janvier 2021 sont disponibles sur le site de la HE2B. Vous pouvez consulter vos résultats en vous connectant à votre compte étudiant.",
	},
	{
		type: "communication",
		id: "6",
		date: new Date("2021-09-03"),
		tags: [NewsType.COMMUNICATION],
		title: "communication administratif",
	},
	{
		type: "other",
		id: "7",
		date: new Date("2021-09-04"),
		tags: [NewsType.OTHER],
		title: "Autres informations",
	},
	{
		type: "sport",
		id: "8",
		date: new Date("2022-09-04"),
		tags: [NewsType.SPORT],
		title: "Journée sportive",
	},
	{
		type: "absence",
		id: "9",
		date: new Date("2023-05-24"),
		tags: [NewsType.ABSENCE],
		teacherName: "Monsieur ABE",
		teacherMonogram: "ABE",
		teacherGender: "M",
		className: "SAR-MAT2",
		classCode: "SAR-MAT2",
		classStartTime: new Date("2023-05-24T08:00:00"),
		classEndTime: new Date("2023-05-24T10:00:00"),
		groupCode: "SAR-MAT2",
		title: "Absence de Monsieur ABE",
		description: "Monsieur ABE sera absent ce jeudi 24 mai. Le cours de SAR-MAT2 de 8h est donc annulé et reporté à une date ultérieure.",
	},
];

export default defaultNews;
